### PR TITLE
Compiles with Ceylon 1.1.1 with tests adjusted accordingly. Bumped to 1.1.1

### PR DESCRIPTION
**Pull request by HenningB**
Previous version used to use mocking modules, packages, functions, and values in a way note compatible to Ceylon 1.1

Tests are now adapted to run with Ceylon 1.1.1

### CODE REVIEW

**Comment by gavinking** [comment]
@loicrouchon or maybe @FroMage could you take a look at this pull request, please?

**Comment by loicrouchon** [comment]
I will take a look at it on Monday, I will not have access to a desktop before

**Comment by gavinking** [comment]
Excellent!

**Comment by loicrouchon** [comment]
Hello,

Before merging your pull request, I would like to know why you removed `mockModule()` / `mockPackage()` functions.
I know mocking is painful and here you took the decision to remove those mocks and create fake modules. the only reason why I didn't do it in the first place was that I didn't knew how many modules I would need nor how to name them. Is there an other reason for which you chose to do it?

I'm not against using real modules as it removes the need for a lot of boilerplate code, it's just that I would have preferred it in its own pull request.



When I merged in local I had some issues with `StringBuilder` in Ant.ceylon and AntProject.ceylon that wasn't present on your branch https://github.com/HenningB/ceylon.build/commits/master/source/ceylon/build/tasks/ant/Ant.ceylon but was on ceylon's one https://github.com/ceylon/ceylon.build/commits/master/source/ceylon/build/tasks/ant/Ant.ceylon
I supposed that you created your branch from an old branch and that you forgot to rebase before pushing.
I managed to do it, but remember that if you do it on your own, Github might be able to automatically merge the pull request and thus save me some time ;)


In any case, a big thanks to you, I'm just waiting for your reply to my first question before merging

**Comment by HenningB** [comment]
The main reason for this commit was that the interfaces `Module`, `Package`, `FunctionDeclaration`, and `ValueDeclaration` are now `sealed` with Ceylon 1.1.0. So the mocking wouldn't work anymore. I reverse engineered your test mocks to become these new modules. Feel free to change them in any way to reflect your tests better.

And thanks for the tip with rebasing. I still need to learn a bit about git. I asked in the mailing list, whether anyone could help me with the back-merge, as the GitHub comparison didn't yield any useful differences to me. Seems the difference was the missing pull request without further changes, but I didn't understand that.

I think you're still using a compiler before the final release of Ceylon 1.1.0. The code I've committed is compiled with a Ceylon compiler a few weeks old, but the `sealed` problem occurred already at the release of 1.1.0. Maybe we should synchronize our compiler versions before we continue with development.

The Ant wrapper actually improved a lot with that pull request I did back then. When all is synchronized again, and I did proper rebasing, I will open a new pull request.

**Comment by HenningB** [comment]
Wait a second, does this pull request include big changes to the Ant wrapper? It was only intended to mend the problem with the sealed interfaces. If you compare the changes here https://github.com/ceylon/ceylon.build/pull/48/files only the mockups are affected.

**Comment by loicrouchon** [comment]
the `sealed` reason is a perfectly valid reason of which I wasn't aware since I didn't work a lot on ceylon.build in previous months.
I now understand better the change.

Concerning my compiler version, I have the latest one (updated yesterday evening) it's just that I directly try to merge your pull request, so no problem on this part.

The only problem was that your branch didn't include some of the latest Ant wrapper changes that have already been merged in ceylon.build (pull request https://github.com/ceylon/ceylon.build/pull/47).
This could have been solved by a rebase on your side before creating the pull request, but I managed to solve the conflicts so no problem with that.

For me everything is now OK, so I will merge the pull request this evening.

**Comment by FroMage** [comment]
Are you also going to merge the `declarative-syntax` branch? If you don't I suppose I can, after this is merged. That's the branch I use.

**Comment by loicrouchon** [comment]
Merged, thank you very much for this pull request.

Concerning `declarative-syntax` it has already been merged in master long time ago, I think you're more speaking about branch `ceylon-plugin`.
Well, I merged this pull request into it but `ceylon-plugin` is not ready to be merged in master, I need to work on the model API and also a lot on documentation that is currently referring to previous version.

**Comment by gavinking** [comment]
So what more is needed to be able to do a release of `ceylon.build`?

**Comment by HenningB** [comment]
Thanks for merging.

**Comment by HenningB** [comment]
@gavinking , @loicrouchon I think another merge of #50 might be good for the release of `ceylon.build`, so the compiler-plugin `ceylon build` compiles the build module within a single ceylon call (for Unix and Windows). It only uses the pre 1.1 compiler options though.

**Pull request merged**
