### PR TITLE
PR for #49 Compile build module within Ceylon

### PR DESCRIPTION
**Pull request by HenningB**
This is the pull reqest for #49 .

The Ceylon compiler plugin is executed with
```
ceylon build [--<compiler-option>=<value>...] <module>/<version> <goal>...
```

Now always compiles the build module, as I don't know yet how to use the cache properly. For changing that look into file `compileModule.ceylon`.

Also added a `ceylon-build.bat` with description. I haven't tested the Unix version of the script though, as it now contains a longer usage explanation. Might been broken now.

### CODE REVIEW

**Comment by HenningB** [comment]
Only supports compiler options of pre 1.1 (or 1.0?).

I've deliberately removed the --out compiler option, and defaulted the option --source=build-source

**Comment by gavinking** [comment]
@loicrouchon are you on top of this?

**Comment by loicrouchon** [comment]
Yes, I'm on it. But no access to a my computer right now. I will take a
look at it on Sunday or Monday evening.

**Comment by loicrouchon** [comment]
I took a look at your work and I have a few remarks:

First, we should not require the user to input the build module name and version.
Otherwise, you will have to do `ceylon build build/1 compile` to launch the `compile` goal which is no good. It should not be longer than `ceylon build compile` (as long as the build module have the default name).
So I think it makes sense to have an optional parameter for the module name in case you have multiples build modules, but the version should never be needed in input (because it's not needed to compile the build module and so we should take the one that module).

Concerning architecture I think we should not use `ceylon.build.tasks.ceylon` to compile the build module itself. For me this is requesting a dependency that is not needed.
Calling the compiler should be as easy as below (don't forget `import com.redhat.ceylon.compiler.java "1.1.1";` in module.ceylon)
```ceylon
CeylonTool tool = CeylonTool();
tool.setToolLoader(loadJavaModule("com.redhat.ceylon.compiler.java", language.version));
tool.bootstrap("compile", "--source=build-source", "build", "other options, ...");
```

I noticed that there were modifications in `ceylon.build.tasks.ant` module and I don't really see what it has to do with this pull request. This might be linked with the fact that you are working directly on master branch.
It would be better to isolate the work related to a pull request by creating its own feature branch.
Here is some documentation about GitHub flow https://guides.github.com/introduction/flow/index.html that explains in a few minutes the feature branch workflow

If you have any questions, let me know, I'll be more than happy to help

**Comment by HenningB** [comment]
Sorry for not answering staight away, but I'm travelling. And I can do the fixes only next Sunday/monday/Tuesday.

So on your comments:

Hmm, thought about it, but then how to destinguish between a module and a goal? And then I didn't knew how to get the version out of a module just compiled. Maybe we can say, if a slash is in the first non-option argument, it's modulename/version otherwise the default is build/1. But this makes the version mandatory, if the module isn't build/1.

Calling the compiler directly might be a better idea.

With the changes in `ceylon.build.tasks.ant` you're right I should do a different pull request. Thanks for the link.

**Comment by HenningB** [comment]
@loicrouchon: Now changed to use the Ceylon compiler directly. Also added compiler options available in 1.1.1.

module/version is now optional, if default build module `build/1` is used. But version is required to distinguish between module and goals.

Compiled binaries go into `./modules`, as I couldn't find a way to load the module from a different directory programatically. Maybe some kind of cache should be used, but then the different projects might overwrite or reuse other's `build/1` module.

**Pull request merged**
